services:
  mongodb:
    container_name: ssbc-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=usr_ssbc
      - MONGO_INITDB_ROOT_PASSWORD=ssbc
      - MONGO_INITDB_DATABASE=ssbc
    volumes:
      - ssbc-mongodb:/data/db

  elasticsearch:
    container_name: ssbc-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    environment:
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    volumes:
        - ssbc-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    container_name: ssbc-kibana
    image: docker.elastic.co/kibana/kibana:8.18.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    volumes:
      - ssbc-kibana:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - elastic

  logstash:
    container_name: ssbc-logstash
    image: docker.elastic.co/logstash/logstash:8.18.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic
    depends_on:
      - elasticsearch

volumes:
  ssbc-mongodb:
  ssbc-elasticsearch:
  ssbc-kibana:

networks:
  elastic:
    driver: bridge