name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login "${{ secrets.REGISTRY_ENDPOINT }}" -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Set TAG from commit hash
        id: vars
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t "${{ secrets.REGISTRY_ENDPOINT }}"/ssbc-api:${TAG} .

      - name: Push commit-tagged image
        run: docker push "${{ secrets.REGISTRY_ENDPOINT }}"/ssbc-api:${TAG}

      - name: Tag as latest and push
        run: |
          docker tag "${{ secrets.REGISTRY_ENDPOINT }}"/ssbc-api:${TAG} "${{ secrets.REGISTRY_ENDPOINT }}"/ssbc-api:latest
          docker push "${{ secrets.REGISTRY_ENDPOINT }}"/ssbc-api:latest

      - name: Deploy
        run: curl "$DEPLOY_ENDPOINT"
        env:
          DEPLOY_ENDPOINT: ${{ secrets.DEPLOY_ENDPOINT }}